[package]
name = "ydcli-rs"
version = "0.1.0"
edition = "2021"
description = "有道词典命令行版 - Youdao Dictionary CLI"
repository = "https://github.com/charleschetty/ydcli-rs"
license = "MIT"
rust-version = "1.80"

[dependencies]
# 零外部依赖 —— 全部使用 Rust 标准库



[profile.release]
opt-level = 3
strip = true  # Automatically strip symbols from the binary.
lto = "fat"
panic = "abort"
codegen-units = 1
